### ISSUE TITLE
ipv6toolkit 2.0-1 build failure in ArchLinux

### ISSUE THREAD

**Issue by AWHubGit** [fgont/ipv6toolkit#67] opened 2020-08-15 17:23 UTC
==> ERROR: A failure occurred in build().
Aborting...
[ipv6toolkit_failure.log](https://github.com/fgont/ipv6toolkit/files/5079196/ipv6toolkit_failure.log)

**Comment by alvarezp** [comment] 2020-08-15 18:16
Duplicate of https://github.com/fgont/ipv6toolkit/pull/54

This is due to `-fno-common` being a new default in GCC 10. It is already fixed in commit 2bde90f3845234490549640dc6ed5712d84969ba.

You may want to backport it to 2.0.

**Comment by fgont** [comment] 2024-10-16 18:18
This one has been fixed. thanks!

**Closed by fgont** 2024-10-16 18:18 UTC
